In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df= pd.read_csv('flight_data_2018_2024.csv')
df

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0     2024        1      1          14          7  2024-01-14   
1     2024        1      1          14          7  2024-01-14   
2     2024        1      1          14          7  2024-01-14   
3     2024        1      1          14          7  2024-01-14   
4     2024        1      1          14          7  2024-01-14   
...    ...      ...    ...         ...        ...         ...   
6306  2024        1      1           2          2  2024-01-02   
6307  2024        1      1           2          2  2024-01-02   
6308  2024        1      1           2          2  2024-01-02   
6309  2024        1      1           2          2  2024-01-02   
6310  2024        1      1           2          2  2024-01-02   

     Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
0                           UA                            UA_CODESHARE   
1                           UA                            UA_CODESHARE   
2                           UA                            UA_CODESHARE   
3                           UA                            UA_CODESHARE   
4                           UA                            UA_CODESHARE   
...                        ...                                     ...   
6306                        UA                            UA_CODESHARE   
6307                        UA                            UA_CODESHARE   
6308                        UA                            UA_CODESHARE   
6309                        UA                            UA_CODESHARE   
6310                        UA                            UA_CODESHARE   

      DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  Div5Airport  \
0                        19977                          UA  ...          NaN   
1                        19977                          UA  ...          NaN   
2                        19977                          UA  ...          NaN   
3                        19977                          UA  ...          NaN   
4                        19977                          UA  ...          NaN   
...                        ...                         ...  ...          ...   
6306                     19977                          UA  ...          NaN   
6307                     19977                          UA  ...          NaN   
6308                     19977                          UA  ...          NaN   
6309                     19977                          UA  ...          NaN   
6310                     19977                          UA  ...          NaN   

      Div5AirportID  Div5AirportSeqID  Div5WheelsOn  Div5TotalGTime  \
0               NaN               NaN           NaN             NaN   
1               NaN               NaN           NaN             NaN   
2               NaN               NaN           NaN             NaN   
3               NaN               NaN           NaN             NaN   
4               NaN               NaN           NaN             NaN   
...             ...               ...           ...             ...   
6306            NaN               NaN           NaN             NaN   
6307            NaN               NaN           NaN             NaN   
6308            NaN               NaN           NaN             NaN   
6309            NaN               NaN           NaN             NaN   
6310            NaN               NaN           NaN             NaN   

     Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  Unnamed: 119  
0                 NaN            NaN         NaN         N           NaN  
1                 NaN            NaN         NaN         N           NaN  
2                 NaN            NaN         NaN         N           NaN  
3                 NaN            NaN         NaN         N           NaN  
4                 NaN            NaN         NaN         N           NaN  
...               ...            ...         ...       ...           ...

In [ ]:
df.shape

(6311, 120)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6311 entries, 0 to 6310
Columns: 120 entries, Year to Unnamed: 119
dtypes: float64(76), int64(23), object(21)
memory usage: 5.8+ MB


In [ ]:
df.isnull().sum()

Year                   0
Quarter                0
Month                  0
DayofMonth             0
DayOfWeek              0
                    ... 
Div5LongestGTime    6311
Div5WheelsOff       6311
Div5TailNum         6311
Duplicate              1
Unnamed: 119        6311
Length: 120, dtype: int64

In [ ]:
df.drop(df.columns[-1], axis=1, inplace=True)

In [ ]:
df

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0     2024        1      1          14          7  2024-01-14   
1     2024        1      1          14          7  2024-01-14   
2     2024        1      1          14          7  2024-01-14   
3     2024        1      1          14          7  2024-01-14   
4     2024        1      1          14          7  2024-01-14   
...    ...      ...    ...         ...        ...         ...   
6306  2024        1      1           2          2  2024-01-02   
6307  2024        1      1           2          2  2024-01-02   
6308  2024        1      1           2          2  2024-01-02   
6309  2024        1      1           2          2  2024-01-02   
6310  2024        1      1           2          2  2024-01-02   

     Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
0                           UA                            UA_CODESHARE   
1                           UA                            UA_CODESHARE   
2                           UA                            UA_CODESHARE   
3                           UA                            UA_CODESHARE   
4                           UA                            UA_CODESHARE   
...                        ...                                     ...   
6306                        UA                            UA_CODESHARE   
6307                        UA                            UA_CODESHARE   
6308                        UA                            UA_CODESHARE   
6309                        UA                            UA_CODESHARE   
6310                        UA                            UA_CODESHARE   

      DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  Div4TailNum  \
0                        19977                          UA  ...          NaN   
1                        19977                          UA  ...          NaN   
2                        19977                          UA  ...          NaN   
3                        19977                          UA  ...          NaN   
4                        19977                          UA  ...          NaN   
...                        ...                         ...  ...          ...   
6306                     19977                          UA  ...          NaN   
6307                     19977                          UA  ...          NaN   
6308                     19977                          UA  ...          NaN   
6309                     19977                          UA  ...          NaN   
6310                     19977                          UA  ...          NaN   

      Div5Airport  Div5AirportID  Div5AirportSeqID  Div5WheelsOn  \
0             NaN            NaN               NaN           NaN   
1             NaN            NaN               NaN           NaN   
2             NaN            NaN               NaN           NaN   
3             NaN            NaN               NaN           NaN   
4             NaN            NaN               NaN           NaN   
...           ...            ...               ...           ...   
6306          NaN            NaN               NaN           NaN   
6307          NaN            NaN               NaN           NaN   
6308          NaN            NaN               NaN           NaN   
6309          NaN            NaN               NaN           NaN   
6310          NaN            NaN               NaN           NaN   

     Div5TotalGTime  Div5LongestGTime Div5WheelsOff Div5TailNum  Duplicate  
0               NaN               NaN           NaN         NaN          N  
1               NaN               NaN           NaN         NaN          N  
2               NaN               NaN           NaN         NaN          N  
3               NaN               NaN           NaN         NaN          N  
4               NaN               NaN           NaN         NaN          N  
...             ...               ...           ...         ...        ...  
6306            NaN

In [ ]:
df.dropna(axis=1, inplace=True)

In [ ]:
df

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0     2024        1      1          14          7  2024-01-14   
1     2024        1      1          14          7  2024-01-14   
2     2024        1      1          14          7  2024-01-14   
3     2024        1      1          14          7  2024-01-14   
4     2024        1      1          14          7  2024-01-14   
...    ...      ...    ...         ...        ...         ...   
6306  2024        1      1           2          2  2024-01-02   
6307  2024        1      1           2          2  2024-01-02   
6308  2024        1      1           2          2  2024-01-02   
6309  2024        1      1           2          2  2024-01-02   
6310  2024        1      1           2          2  2024-01-02   

     Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
0                           UA                            UA_CODESHARE   
1                           UA                            UA_CODESHARE   
2                           UA                            UA_CODESHARE   
3                           UA                            UA_CODESHARE   
4                           UA                            UA_CODESHARE   
...                        ...                                     ...   
6306                        UA                            UA_CODESHARE   
6307                        UA                            UA_CODESHARE   
6308                        UA                            UA_CODESHARE   
6309                        UA                            UA_CODESHARE   
6310                        UA                            UA_CODESHARE   

      DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  DepTimeBlk  \
0                        19977                          UA  ...   1700-1759   
1                        19977                          UA  ...   0800-0859   
2                        19977                          UA  ...   1500-1559   
3                        19977                          UA  ...   0600-0659   
4                        19977                          UA  ...   1300-1359   
...                        ...                         ...  ...         ...   
6306                     19977                          UA  ...   1400-1459   
6307                     19977                          UA  ...   1200-1259   
6308                     19977                          UA  ...   1600-1659   
6309                     19977                          UA  ...   2000-2059   
6310                     19977                          UA  ...   1400-1459   

     CRSArrTime  ArrTimeBlk Cancelled  Diverted  CRSElapsedTime  Flights  \
0          1922   1900-1959       0.0       0.0           104.0      1.0   
1           934   0900-0959       0.0       0.0            79.0      1.0   
2          1656   1600-1659       0.0       0.0            76.0      1.0   
3           758   0700-0759       0.0       0.0            88.0      1.0   
4          1603   1600-1659       0.0       0.0           123.0      1.0   
...         ...         ...       ...       ...             ...      ...   
6306       1533   1500-1559       0.0       0.0            68.0      1.0   
6307       1320   1300-1359       0.0       0.0            65.0      1.0   
6308       1725   1700-1759       0.0       0.0            70.0      1.0   
6309       2316   2300-2359       0.0       0.0           131.0      1.0   
6310       1609   1600-1659       0.0       0.0           107.0      1.0   

      Distance DistanceGroup DivAirportLandings  
0        209.0             1                  0  
1        212.0             1                  0  
2        209.0             1                  0  
3        258.0             2                  0  
4        696.0             3                  0  
...        ...           ...                ...  
6306     140.0             1                  0  
6307     140.0             1                  0  
6308     201.0          

In [ ]:
df.drop(['Year'],inplace=True, axis=1)

In [ ]:
df.drop(columns=['Quarter','Month'], axis=1, inplace=True)

In [ ]:
df

DayofMonth  DayOfWeek  FlightDate Marketing_Airline_Network  \
0             14          7  2024-01-14                        UA   
1             14          7  2024-01-14                        UA   
2             14          7  2024-01-14                        UA   
3             14          7  2024-01-14                        UA   
4             14          7  2024-01-14                        UA   
...          ...        ...         ...                       ...   
6306           2          2  2024-01-02                        UA   
6307           2          2  2024-01-02                        UA   
6308           2          2  2024-01-02                        UA   
6309           2          2  2024-01-02                        UA   
6310           2          2  2024-01-02                        UA   

     Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
0                               UA_CODESHARE                     19977   
1                               UA_CODESHARE                     19977   
2                               UA_CODESHARE                     19977   
3                               UA_CODESHARE                     19977   
4                               UA_CODESHARE                     19977   
...                                      ...                       ...   
6306                            UA_CODESHARE                     19977   
6307                            UA_CODESHARE                     19977   
6308                            UA_CODESHARE                     19977   
6309                            UA_CODESHARE                     19977   
6310                            UA_CODESHARE                     19977   

     IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
0                             UA                             4432   
1                             UA                             4430   
2                             UA                             4429   
3                             UA                             4428   
4                             UA                             4427   
...                          ...                              ...   
6306                          UA                             6290   
6307                          UA                             6285   
6308                          UA                             6277   
6309                          UA                             6275   
6310                          UA                             6273   

     Operating_Airline   DOT_ID_Operating_Airline  ... DepTimeBlk  CRSArrTime  \
0                    G7                     20500  ...  1700-1759        1922   
1                    G7                     20500  ...  0800-0859         934   
2                    G7                     20500  ...  1500-1559        1656   
3                    G7                     20500  ...  0600-0659         758   
4                    G7                     20500  ...  1300-1359        1603   
...                 ...                       ...  ...        ...         ...   
6306                 YV                     20378  ...  1400-1459        1533   
6307                 YV                     20378  ...  1200-1259        1320   
6308                 YV                     20378  ...  1600-1659        1725   
6309                 YV                     20378  ...  2000-2059        2316   
6310                 YV                     20378  ...  1400-1459        1609   

      ArrTimeBlk  Cancelled  Diverted CRSElapsedTime Flights Distance  \
0      1900-1959        0.0       0.0          104.0     1.0    209.0   
1      0900-0959        0.0       0.0           79.0     1.0    212.0   
2      1600-1659        0.0       0.0           76.0     1.0    209.0   
3      0700-0759        0.0       0.0           88.0     1.0    258.0   
4      1600-1659        0.0       0.0          123.0     1.0    696.0   
...          ...        ...       ...           

In [ ]:
df.columns

Index(['DayofMonth', 'DayOfWeek', 'FlightDate', 'Marketing_Airline_Network',
       'Operated_or_Branded_Code_Share_Partners', 'DOT_ID_Marketing_Airline',
       'IATA_Code_Marketing_Airline', 'Flight_Number_Marketing_Airline',
       'Operating_Airline ', 'DOT_ID_Operating_Airline',
       'IATA_Code_Operating_Airline', 'Flight_Number_Operating_Airline',
       'OriginAirportID', 'OriginAirportSeqID', 'OriginCityMarketID', 'Origin',
       'OriginCityName', 'OriginState', 'OriginStateFips', 'OriginStateName',
       'OriginWac', 'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID',
       'Dest', 'DestCityName', 'DestState', 'DestStateFips', 'DestStateName',
       'DestWac', 'CRSDepTime', 'DepTimeBlk', 'CRSArrTime', 'ArrTimeBlk',
       'Cancelled', 'Diverted', 'CRSElapsedTime', 'Flights', 'Distance',
       'DistanceGroup', 'DivAirportLandings'],
      dtype='object')

In [ ]:
df['Cancelled'].unique()

array([0., 1.])

In [ ]:
df['Diverted'].unique()

array([0., 1.])

In [ ]:
df['IATA_Code_Marketing_Airline'].unique()

array(['UA'], dtype=object)

#Logistic Regression

In [ ]:
y= df.iloc[:,-6].values
y

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
X= df.drop(['Diverted'],axis=1)
X

DayofMonth  DayOfWeek  FlightDate Marketing_Airline_Network  \
0             14          7  2024-01-14                        UA   
1             14          7  2024-01-14                        UA   
2             14          7  2024-01-14                        UA   
3             14          7  2024-01-14                        UA   
4             14          7  2024-01-14                        UA   
...          ...        ...         ...                       ...   
6306           2          2  2024-01-02                        UA   
6307           2          2  2024-01-02                        UA   
6308           2          2  2024-01-02                        UA   
6309           2          2  2024-01-02                        UA   
6310           2          2  2024-01-02                        UA   

     Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
0                               UA_CODESHARE                     19977   
1                               UA_CODESHARE                     19977   
2                               UA_CODESHARE                     19977   
3                               UA_CODESHARE                     19977   
4                               UA_CODESHARE                     19977   
...                                      ...                       ...   
6306                            UA_CODESHARE                     19977   
6307                            UA_CODESHARE                     19977   
6308                            UA_CODESHARE                     19977   
6309                            UA_CODESHARE                     19977   
6310                            UA_CODESHARE                     19977   

     IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
0                             UA                             4432   
1                             UA                             4430   
2                             UA                             4429   
3                             UA                             4428   
4                             UA                             4427   
...                          ...                              ...   
6306                          UA                             6290   
6307                          UA                             6285   
6308                          UA                             6277   
6309                          UA                             6275   
6310                          UA                             6273   

     Operating_Airline   DOT_ID_Operating_Airline  ... CRSDepTime  DepTimeBlk  \
0                    G7                     20500  ...       1738   1700-1759   
1                    G7                     20500  ...        815   0800-0859   
2                    G7                     20500  ...       1540   1500-1559   
3                    G7                     20500  ...        630   0600-0659   
4                    G7                     20500  ...       1300   1300-1359   
...                 ...                       ...  ...        ...         ...   
6306                 YV                     20378  ...       1425   1400-1459   
6307                 YV                     20378  ...       1215   1200-1259   
6308                 YV                     20378  ...       1615   1600-1659   
6309                 YV                     20378  ...       2005   2000-2059   
6310                 YV                     20378  ...       1422   1400-1459   

      CRSArrTime  ArrTimeBlk  Cancelled CRSElapsedTime Flights Distance  \
0           1922   1900-1959        0.0          104.0     1.0    209.0   
1            934   0900-0959        0.0           79.0     1.0    212.0   
2           1656   1600-1659        0.0           76.0     1.0    209.0   
3            758   0700-0759        0.0           88.0     1.0    258.0   
4           1603   1600-1659        0.0          123.0     1.0    696.0   
...          ...         ...        

#Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
for col in X.columns: # Iterate over column names directly
  X[col] = le.fit_transform(X[col]) # Apply LabelEncoder to each column

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.34, random_state = 0)

In [ ]:
print(y_test)

[0. 0. 0. ... 0. 0. 0.]


In [ ]:
X_train[0:5]

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
4603           4          5           4                          0   
5084           3          4           3                          0   
1986           8          2           8                          0   
4441           4          5           4                          0   
6228           1          2           1                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
4603                                        0                         0   
5084                                        0                         0   
1986                                        0                         0   
4441                                        0                         0   
6228                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
4603                            0                               55   
5084                            0                              117   
1986                            0                              532   
4441                            0                              247   
6228                            0                               44   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
4603                   0                         1  ...         213   
5084                   0                         1  ...         204   
1986                   2                         0  ...         314   
4441                   1                         2  ...          90   
6228                   0                         1  ...         258   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
4603           8         379          10          0              60        0   
5084           8         366          10          0              71        0   
1986          11         445          12          0              17        0   
4441           4         134           4          0              19        0   
6228          10         412          11          0              74        0   

      Distance  DistanceGroup  DivAirportLandings  
4603       115              2                   0  
5084       123              2                   0  
1986        24              0                   0  
4441        13              0                   0  
6228       101              2                   0  

[5 rows x 40 columns]

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train[0:5]

array([[-0.64857676,  0.99019918, -0.64857676,  0.        ,  0.        ,
         0.        ,  0.        , -1.35916997, -1.21962433,  0.21821396,
        -1.21962433, -1.35916997, -0.90699864, -0.90699864, -1.43900045,
        -0.90699864, -0.96477479, -1.78890094, -1.77090397, -1.77090397,
         1.07057848,  1.87421861,  1.87421861,  2.19960503,  1.87421861,
         1.39267344, -0.61033494, -0.52327528, -0.52327528,  0.32614524,
         0.05292553,  0.0744688 ,  0.3668462 ,  0.37400333, -0.23387474,
         0.36556591,  0.        ,  1.1096899 ,  0.71325486, -0.06521739],
       [-0.95192569,  0.42954399, -0.95192569,  0.        ,  0.        ,
         0.        ,  0.        , -1.06676419, -1.21962433,  0.21821396,
        -1.21962433, -1.06676419,  2.05425328,  2.05425328, -0.21276101,
         2.05425328,  1.45463921, -0.5922506 , -0.50535038, -0.50535038,
         0.31621312, -0.14503572, -0.14503572, -0.6473635 , -0.14503572,
         1.62136053,  0.93607793,  1.00217278,  1.

In [ ]:
print(X_test)

[[-1.25527461 -0.1311112  -1.25527461 ...  1.53301886  1.62957396
  -0.06521739]
 [-0.34522783  1.55085438 -0.34522783 ...  1.53301886  1.62957396
  -0.06521739]
 [-0.64857676  0.99019918 -0.64857676 ... -0.37196142 -0.20306423
  -0.06521739]
 ...
 [ 0.56481895 -0.6917664   0.56481895 ... -1.54787518 -1.11938332
  -0.06521739]
 [-0.64857676  0.99019918 -0.64857676 ...  1.53301886  1.62957396
  -0.06521739]
 [-1.25527461 -0.1311112  -1.25527461 ...  2.12097573  3.46221214
  -0.06521739]]


#Training Logistic Regression model on training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

#Predict Test results

In [ ]:
y_test

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2137    0]
 [   0    9]]


1.0

#KNN model

In [ ]:
X

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
0             12          6          12                          0   
1             12          6          12                          0   
2             12          6          12                          0   
3             12          6          12                          0   
4             12          6          12                          0   
...          ...        ...         ...                        ...   
6306           0          1           0                          0   
6307           0          1           0                          0   
6308           0          1           0                          0   
6309           0          1           0                          0   
6310           0          1           0                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
0                                           0                         0   
1                                           0                         0   
2                                           0                         0   
3                                           0                         0   
4                                           0                         0   
...                                       ...                       ...   
6306                                        0                         0   
6307                                        0                         0   
6308                                        0                         0   
6309                                        0                         0   
6310                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
0                               0                              235   
1                               0                              233   
2                               0                              232   
3                               0                              231   
4                               0                              230   
...                           ...                              ...   
6306                            0                              672   
6307                            0                              669   
6308                            0                              663   
6309                            0                              661   
6310                            0                              659   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
0                      1                         2  ...         350   
1                      1                         2  ...          63   
2                      1                         2  ...         277   
3                      1                         2  ...          24   
4                      1                         2  ...         204   
...                  ...                       ...  ...         ...   
6306                   2                         0  ...         240   
6307                   2                         0  ...         181   
6308                   2                         0  ...         297   
6309                   2                         0  ...         403   
6310                   2                         0  ...         238   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
0             12         505          13          0              48        0   
1              3          90           3          0              23        0   
2             10         403          10          0              20        0   
3              1          41           1          0              32        0   
4              8         362          10          0              67        0   
...          ...         ...         ...        ...             ...      ...   
6306      

In [ ]:
y

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.29, random_state = 0)

In [ ]:
X_train

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
4568           4          5           4                          0   
470           11          5          11                          0   
5832           1          2           1                          0   
2303           8          2           8                          0   
1961           8          2           8                          0   
...          ...        ...         ...                        ...   
4931           3          4           3                          0   
3264           6          0           6                          0   
1653           9          3           9                          0   
2607           7          1           7                          0   
2732           7          1           7                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
4568                                        0                         0   
470                                         0                         0   
5832                                        0                         0   
2303                                        0                         0   
1961                                        0                         0   
...                                       ...                       ...   
4931                                        0                         0   
3264                                        0                         0   
1653                                        0                         0   
2607                                        0                         0   
2732                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
4568                            0                               91   
470                             0                              322   
5832                            0                              557   
2303                            0                              138   
1961                            0                              569   
...                           ...                              ...   
4931                            0                              358   
3264                            0                              369   
1653                            0                              233   
2607                            0                              472   
2732                            0                              323   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
4568                   0                         1  ...         388   
470                    1                         2  ...         353   
5832                   2                         0  ...         327   
2303                   0                         1  ...         265   
1961                   2                         0  ...          35   
...                  ...                       ...  ...         ...   
4931                   0                         1  ...         215   
3264                   0                         1  ...          70   
1653                   1                         2  ...          63   
2607                   2                         0  ...         166   
2732                   1                         2  ...         418   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
4568          14         578          15          0              47        0   
470           12         504          13          0              95        0   
5832          12         437          11          0              49        0   
2303          10         407          11          0              56        0   
1961           2          71           2          0              54        0   
...          ...         ...         ...        ...             ...      ...   
4931      

In [ ]:
y_train

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
X_test

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
5323           2          3           2                          0   
3718           5          6           5                          0   
4381           4          5           4                          0   
3471           6          0           6                          0   
4355           4          5           4                          0   
...          ...        ...         ...                        ...   
1237          10          4          10                          0   
507           11          5          11                          0   
4767           3          4           3                          0   
88            12          6          12                          0   
2753           7          1           7                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
5323                                        0                         0   
3718                                        0                         0   
4381                                        0                         0   
3471                                        0                         0   
4355                                        0                         0   
...                                       ...                       ...   
1237                                        0                         0   
507                                         0                         0   
4767                                        0                         0   
88                                          0                         0   
2753                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
5323                            0                              520   
3718                            0                              479   
4381                            0                              351   
3471                            0                               83   
4355                            0                              393   
...                           ...                              ...   
1237                            0                               47   
507                             0                              247   
4767                            0                              538   
88                              0                              118   
2753                            0                              263   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
5323                   2                         0  ...         166   
3718                   2                         0  ...         403   
4381                   0                         1  ...         107   
3471                   0                         1  ...          11   
4355                   0                         1  ...         248   
...                  ...                       ...  ...         ...   
1237                   0                         1  ...         401   
507                    1                         2  ...         141   
4767                   2                         0  ...         168   
88                     0                         1  ...         252   
2753                   1                         2  ...         258   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
5323           6         294           8          0              89        0   
3718          15         618          16          0              90        0   
4381           4         170           5          0              32        0   
3471           1          30           1          0              39        0   
4355           9         367          10          0              32        0   
...          ...         ...         ...        ...             ...      ...   
1237      

In [ ]:
y_test

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.64775371,  0.99325401, -0.64775371, ..., -0.0857519 ,
        -0.20212926, -0.06287341],
       [ 1.46934439,  0.99325401,  1.46934439, ...,  1.30071388,
         0.71071256, -0.06287341],
       [-1.55508146, -0.69546628, -1.55508146, ...,  0.10224346,
        -0.20212926, -0.06287341],
       ...,
       [ 0.86445922, -0.13255952,  0.86445922, ..., -0.97872986,
        -1.11497108, -0.06287341],
       [ 0.25957405, -1.25837304,  0.25957405, ...,  1.34771272,
         0.71071256, -0.06287341],
       [ 0.25957405, -1.25837304,  0.25957405, ..., -1.11972638,
        -1.11497108, -0.06287341]])

In [ ]:
X_test

array([[-1.25263888, -0.13255952, -1.25263888, ...,  1.53570808,
         1.62355438, -0.06287341],
       [-0.34531112,  1.55616077, -0.34531112, ...,  1.53570808,
         1.62355438, -0.06287341],
       [-0.64775371,  0.99325401, -0.64775371, ..., -0.36774494,
        -0.20212926, -0.06287341],
       ...,
       [-0.95019629,  0.43034724, -0.95019629, ..., -0.06225248,
        -0.20212926, -0.06287341],
       [ 1.77178698,  1.55616077,  1.77178698, ..., -1.21372406,
        -1.11497108, -0.06287341],
       [ 0.25957405, -1.25837304,  0.25957405, ..., -0.64973798,
        -0.20212926, -0.06287341]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 17, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=17)

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1822    0]
 [   0    9]]


1.0

#SVM Classifier Model

In [ ]:
X

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
0             12          6          12                          0   
1             12          6          12                          0   
2             12          6          12                          0   
3             12          6          12                          0   
4             12          6          12                          0   
...          ...        ...         ...                        ...   
6306           0          1           0                          0   
6307           0          1           0                          0   
6308           0          1           0                          0   
6309           0          1           0                          0   
6310           0          1           0                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
0                                           0                         0   
1                                           0                         0   
2                                           0                         0   
3                                           0                         0   
4                                           0                         0   
...                                       ...                       ...   
6306                                        0                         0   
6307                                        0                         0   
6308                                        0                         0   
6309                                        0                         0   
6310                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
0                               0                              235   
1                               0                              233   
2                               0                              232   
3                               0                              231   
4                               0                              230   
...                           ...                              ...   
6306                            0                              672   
6307                            0                              669   
6308                            0                              663   
6309                            0                              661   
6310                            0                              659   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
0                      1                         2  ...         350   
1                      1                         2  ...          63   
2                      1                         2  ...         277   
3                      1                         2  ...          24   
4                      1                         2  ...         204   
...                  ...                       ...  ...         ...   
6306                   2                         0  ...         240   
6307                   2                         0  ...         181   
6308                   2                         0  ...         297   
6309                   2                         0  ...         403   
6310                   2                         0  ...         238   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
0             12         505          13          0              48        0   
1              3          90           3          0              23        0   
2             10         403          10          0              20        0   
3              1          41           1          0              32        0   
4              8         362          10          0              67        0   
...          ...         ...         ...        ...             ...      ...   
6306      

In [ ]:
y

array([0., 0., 0., ..., 0., 0., 0.])

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.28, random_state = 0)

In [ ]:
X_train

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
3628           5          6           5                          0   
2824           7          1           7                          0   
1284           9          3           9                          0   
658           11          5          11                          0   
1329           9          3           9                          0   
...          ...        ...         ...                        ...   
4931           3          4           3                          0   
3264           6          0           6                          0   
1653           9          3           9                          0   
2607           7          1           7                          0   
2732           7          1           7                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
3628                                        0                         0   
2824                                        0                         0   
1284                                        0                         0   
658                                         0                         0   
1329                                        0                         0   
...                                       ...                       ...   
4931                                        0                         0   
3264                                        0                         0   
1653                                        0                         0   
2607                                        0                         0   
2732                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
3628                            0                              595   
2824                            0                              190   
1284                            0                              725   
658                             0                               57   
1329                            0                              647   
...                           ...                              ...   
4931                            0                              358   
3264                            0                              369   
1653                            0                              233   
2607                            0                              472   
2732                            0                              323   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
3628                   2                         0  ...         106   
2824                   1                         2  ...          50   
1284                   2                         0  ...         398   
658                    0                         1  ...         195   
1329                   2                         0  ...         324   
...                  ...                       ...  ...         ...   
4931                   0                         1  ...         215   
3264                   0                         1  ...          70   
1653                   1                         2  ...          63   
2607                   2                         0  ...         166   
2732                   1                         2  ...         418   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
3628           4         199           5          0              70        0   
2824           2         113           4          0              37        0   
1284          14         585          15          0              44        0   
658            7         268           7          0              16        0   
1329          12         446          12          0              66        0   
...          ...         ...         ...        ...             ...      ...   
4931      

In [ ]:
y_train

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
X_test

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
5323           2          3           2                          0   
3718           5          6           5                          0   
4381           4          5           4                          0   
3471           6          0           6                          0   
4355           4          5           4                          0   
...          ...        ...         ...                        ...   
4019           5          6           5                          0   
435           11          5          11                          0   
269           11          5          11                          0   
4922           3          4           3                          0   
817           10          4          10                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
5323                                        0                         0   
3718                                        0                         0   
4381                                        0                         0   
3471                                        0                         0   
4355                                        0                         0   
...                                       ...                       ...   
4019                                        0                         0   
435                                         0                         0   
269                                         0                         0   
4922                                        0                         0   
817                                         0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
5323                            0                              520   
3718                            0                              479   
4381                            0                              351   
3471                            0                               83   
4355                            0                              393   
...                           ...                              ...   
4019                            0                               89   
435                             0                              376   
269                             0                              583   
4922                            0                              378   
817                             0                              558   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
5323                   2                         0  ...         166   
3718                   2                         0  ...         403   
4381                   0                         1  ...         107   
3471                   0                         1  ...          11   
4355                   0                         1  ...         248   
...                  ...                       ...  ...         ...   
4019                   0                         1  ...          92   
435                    0                         1  ...          88   
269                    2                         0  ...         349   
4922                   0                         1  ...         191   
817                    2                         0  ...         299   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
5323           6         294           8          0              89        0   
3718          15         618          16          0              90        0   
4381           4         170           5          0              32        0   
3471           1          30           1          0              39        0   
4355           9         367          10          0              32        0   
...          ...         ...         ...        ...             ...      ...   
4019      

In [ ]:
y_test

array([0., 0., 0., ..., 0., 0., 0.])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.34859545,  1.55405928, -0.34859545, ...,  1.2086825 ,
         0.71234017, -0.06243422],
       [ 0.25608921, -1.26052026,  0.25608921, ..., -0.85868465,
        -1.11239137, -0.06243422],
       [ 0.86077387, -0.13468844,  0.86077387, ...,  0.17499893,
        -0.2000256 , -0.06243422],
       ...,
       [ 0.86077387, -0.13468844,  0.86077387, ..., -0.97614869,
        -1.11239137, -0.06243422],
       [ 0.25608921, -1.26052026,  0.25608921, ...,  1.34963935,
         0.71234017, -0.06243422],
       [ 0.25608921, -1.26052026,  0.25608921, ..., -1.11710554,
        -1.11239137, -0.06243422]])

In [ ]:
X_test

array([[-1.25562243, -0.13468844, -1.25562243, ...,  1.53758182,
         1.62470594, -0.06243422],
       [-0.34859545,  1.55405928, -0.34859545, ...,  1.53758182,
         1.62470594, -0.06243422],
       [-0.65093778,  0.99114338, -0.65093778, ..., -0.36533567,
        -0.2000256 , -0.06243422],
       ...,
       [ 1.46545853,  0.99114338,  1.46545853, ..., -1.30504801,
        -1.11239137, -0.06243422],
       [-0.95328011,  0.42822747, -0.95328011, ..., -0.55327813,
        -0.2000256 , -0.06243422],
       [ 1.1631162 ,  0.42822747,  1.1631162 , ...,  1.4671034 ,
         1.62470594, -0.06243422]])

#Training SVM classifier model on training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='poly', random_state=0)

#Predicting Test set result


In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1759    0]
 [   0    9]]


1.0

#Training Naive Bayes Classification model

In [ ]:
X

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
0             12          6          12                          0   
1             12          6          12                          0   
2             12          6          12                          0   
3             12          6          12                          0   
4             12          6          12                          0   
...          ...        ...         ...                        ...   
6306           0          1           0                          0   
6307           0          1           0                          0   
6308           0          1           0                          0   
6309           0          1           0                          0   
6310           0          1           0                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
0                                           0                         0   
1                                           0                         0   
2                                           0                         0   
3                                           0                         0   
4                                           0                         0   
...                                       ...                       ...   
6306                                        0                         0   
6307                                        0                         0   
6308                                        0                         0   
6309                                        0                         0   
6310                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
0                               0                              235   
1                               0                              233   
2                               0                              232   
3                               0                              231   
4                               0                              230   
...                           ...                              ...   
6306                            0                              672   
6307                            0                              669   
6308                            0                              663   
6309                            0                              661   
6310                            0                              659   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
0                      1                         2  ...         350   
1                      1                         2  ...          63   
2                      1                         2  ...         277   
3                      1                         2  ...          24   
4                      1                         2  ...         204   
...                  ...                       ...  ...         ...   
6306                   2                         0  ...         240   
6307                   2                         0  ...         181   
6308                   2                         0  ...         297   
6309                   2                         0  ...         403   
6310                   2                         0  ...         238   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
0             12         505          13          0              48        0   
1              3          90           3          0              23        0   
2             10         403          10          0              20        0   
3              1          41           1          0              32        0   
4              8         362          10          0              67        0   
...          ...         ...         ...        ...             ...      ...   
6306      

In [ ]:
y

array([0., 0., 0., ..., 0., 0., 0.])

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.365, random_state = 0)

In [ ]:
X_train

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
4831           3          4           3                          0   
5526           2          3           2                          0   
6101           1          2           1                          0   
2300           8          2           8                          0   
2549           7          1           7                          0   
...          ...        ...         ...                        ...   
4931           3          4           3                          0   
3264           6          0           6                          0   
1653           9          3           9                          0   
2607           7          1           7                          0   
2732           7          1           7                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
4831                                        0                         0   
5526                                        0                         0   
6101                                        0                         0   
2300                                        0                         0   
2549                                        0                         0   
...                                       ...                       ...   
4931                                        0                         0   
3264                                        0                         0   
1653                                        0                         0   
2607                                        0                         0   
2732                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
4831                            0                              466   
5526                            0                              241   
6101                            0                              190   
2300                            0                              142   
2549                            0                              536   
...                           ...                              ...   
4931                            0                              358   
3264                            0                              369   
1653                            0                              233   
2607                            0                              472   
2732                            0                              323   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
4831                   2                         0  ...         256   
5526                   1                         2  ...         229   
6101                   1                         2  ...         137   
2300                   0                         1  ...          48   
2549                   2                         0  ...         382   
...                  ...                       ...  ...         ...   
4931                   0                         1  ...         215   
3264                   0                         1  ...          70   
1653                   1                         2  ...          63   
2607                   2                         0  ...         166   
2732                   1                         2  ...         418   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
4831           9         383          10          0              33        0   
5526           9         337           9          0              28        0   
6101           5         234           7          0              78        0   
2300           2          77           3          0              34        0   
2549          14         563          14          0              55        0   
...          ...         ...         ...        ...             ...      ...   
4931      

In [ ]:
y_train

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:

X_test

DayofMonth  DayOfWeek  FlightDate  Marketing_Airline_Network  \
5323           2          3           2                          0   
3718           5          6           5                          0   
4381           4          5           4                          0   
3471           6          0           6                          0   
4355           4          5           4                          0   
...          ...        ...         ...                        ...   
3740           5          6           5                          0   
2706           7          1           7                          0   
6303           0          1           0                          0   
6092           1          2           1                          0   
3132           6          0           6                          0   

      Operated_or_Branded_Code_Share_Partners  DOT_ID_Marketing_Airline  \
5323                                        0                         0   
3718                                        0                         0   
4381                                        0                         0   
3471                                        0                         0   
4355                                        0                         0   
...                                       ...                       ...   
3740                                        0                         0   
2706                                        0                         0   
6303                                        0                         0   
6092                                        0                         0   
3132                                        0                         0   

      IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
5323                            0                              520   
3718                            0                              479   
4381                            0                              351   
3471                            0                               83   
4355                            0                              393   
...                           ...                              ...   
3740                            0                              456   
2706                            0                              367   
6303                            0                              676   
6092                            0                              199   
3132                            0                              505   

      Operating_Airline   DOT_ID_Operating_Airline  ...  CRSDepTime  \
5323                   2                         0  ...         166   
3718                   2                         0  ...         403   
4381                   0                         1  ...         107   
3471                   0                         1  ...          11   
4355                   0                         1  ...         248   
...                  ...                       ...  ...         ...   
3740                   2                         0  ...         186   
2706                   0                         1  ...         290   
6303                   2                         0  ...          35   
6092                   1                         2  ...         223   
3132                   2                         0  ...         235   

      DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  CRSElapsedTime  Flights  \
5323           6         294           8          0              89        0   
3718          15         618          16          0              90        0   
4381           4         170           5          0              32        0   
3471           1          30           1          0              39        0   
4355           9         367          10          0              32        0   
...          ...         ...         ...        ...             ...      ...   
3740      

In [ ]:
y_test

array([0., 0., 0., ..., 0., 0., 0.])

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.95459292,  0.42643742, -0.95459292, ..., -0.10453087,
        -0.19776659, -0.06649633],
       [-1.25795193, -0.13380348, -1.25795193, ..., -1.09223055,
        -1.11389459, -0.06649633],
       [-1.56131095, -0.69404437, -1.56131095, ...,  0.83613549,
         0.71836142, -0.06649633],
       ...,
       [ 0.86556117, -0.13380348,  0.86556117, ..., -0.97464726,
        -1.11389459, -0.06649633],
       [ 0.25884314, -1.25428526,  0.25884314, ...,  1.35350198,
         0.71836142, -0.06649633],
       [ 0.25884314, -1.25428526,  0.25884314, ..., -1.11574721,
        -1.11389459, -0.06649633]])

In [ ]:
X_test

array([[-1.25795193, -0.13380348, -1.25795193, ...,  1.54163526,
         1.63448942, -0.06649633],
       [-0.34787489,  1.5469192 , -0.34787489, ...,  1.54163526,
         1.63448942, -0.06649633],
       [-0.6512339 ,  0.98667831, -0.6512339 , ..., -0.36321412,
        -0.19776659, -0.06649633],
       ...,
       [-1.86466996, -1.25428526, -1.86466996, ...,  0.17766903,
        -0.19776659, -0.06649633],
       [-1.56131095, -0.69404437, -1.56131095, ...,  1.09481874,
         0.71836142, -0.06649633],
       [-0.04451587, -1.81452616, -0.04451587, ...,  1.25943535,
         0.71836142, -0.06649633]])

##Gaussian NB

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2295    0]
 [   0    9]]


1.0

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.365, random_state = 0)

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2295    0]
 [   4    5]]


0.9982638888888888

#Training Decision Tree Classification model

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.365, random_state = 0)

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2295    0]
 [   0    9]]


1.0

#Random Forest Classification model

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.365, random_state = 0)

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Splitting dataset into Train Set and Test Set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.365, random_state = 0)

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training Random Forest Classification model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 15, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=15, random_state=0)

#Predicting Test set result

In [ ]:
y_pred= classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#Making Confusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2295    0]
 [   1    8]]


0.9995659722222222

In [ ]:
my_dict= {
    "Logistic Regression": 1,
    "KNN": 1,
    "SVM": 1,
    "Naive Bayes (Gaussain)": 1.0,
    "Naive Bayes (Bernoulli)": 0.9982638888888888,
    "Decision Tree": 1,
    "Random Forest": 0.9995659722222222
}

In [ ]:
Series= pd.Series(my_dict)
Series

Logistic Regression        1.000000
KNN                        1.000000
SVM                        1.000000
Naive Bayes (Gaussain)     1.000000
Naive Bayes (Bernoulli)    0.998264
Decision Tree              1.000000
Random Forest              0.999566
dtype: float64